### ISSUE TITLE
Add player domain to the Party Sheet

### ISSUE THREAD

**Issue by Gtaray** [Gtaray/FG_KingdomsAndWarfare#58]
Since the party sheet is public and can be accessed by all players, we could create a publicly editable domain sheet on a new tab of the party sheet.

**Comment by MeAndUnique** [comment]
If the contents of the domain window are moved into another windowclass, that could be used as a subwindow in both the current domain window and a new tab on the party sheet.

**Comment by Gtaray** [comment]
This currently exists in the powerdiceAutomation branch, and will be merged in soon.
