### ISSUE TITLE
Power Dice Effects

### ISSUE THREAD

**Issue by MeAndUnique** [Gtaray/FG_KingdomsAndWarfare#65]
Add support for effects based on the power dice being used. When a power die is used, it should add an effect to the user indicating its value. Support should be added for other effects to use the power dice value(s) in their calculations. The other effects should also be able to control whether the initial power dice effect(s) is removed on use or decremented.

**Comment by Gtaray** [comment]
When a player rolls a power die, an effect "POWERDIE: #" is put on the PC, where # is the power die they pulled.

Effects can interact with that effect using the PDIE shorthand in place of numbers in effects. Ex. ATK: PDIE

This also works with multipliers, using the '#x' notation. Ex. ATK: 2x PDIE

Decrementing is handled with the "DECREMENT" effect clause. Ex. DECREMENT; ATK: 2x PDIE

When an actor with a 'decrement' effect ends their turn, the powerdie effect on that actor is reduced by 1. If it is reduced to 0, both the powerdie effect and the effect with 'decrement' are removed from the actor. 

Currently not supported: Negative PDIE (-PDIE), and PDIE effects on actors who do not have a powerdie effect (i.e. enemies).
